language: csharp
mono: none
dotnet: 3.1.100
dist: bionic
env:
  - NO_ILREPACK=1
script:
  - cd ./Spectrum.Native
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Spectrum
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Prism
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Prism.Pipeline
  - dotnet build -c Debug -p:Platform=x64