language: csharp
mono: none
dotnet: 2.1.502
dist: trusty
before_install:
  - sudo apt-get install -y mono-complete
script:
  - dotnet restore
  - cd ./Spectrum.Native
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Spectrum
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Prism.Pipeline
  - dotnet build -c Debug -p:Platform=x64
  #- cd ../Prism
  # workaround for missing .net target pack
  #- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  #- dotnet build -c Debug
