language: csharp
mono: none
dotnet: 3.0.101
dist: bionic
script:
  - dotnet restore
  - cd ./Spectrum.Native
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Spectrum
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Prism
  - dotnet build -c Debug -p:Platform=x64
  - cd ../Prism.Pipeline
  - dotnet build -c Debug -p:Platform=x64