language: csharp
mono: none
dotnet: 3.0.101
dist: xenial
script:
  - dotnet restore
  - cd ./Spectrum.Native
  - dotnet build -c Debug -p:Platform=x64
  #- dotnet build -c Release -p:Platform=x64
  - cd ../Spectrum
  - dotnet build -c Debug -p:Platform=x64
  #- dotnet build -c Release -p:Platform=x64